[package]
name = "lab_03"
version = "0.1.0"
authors = ["Perestoronin Pavel <pavel.perestoronin@qoollo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
