[package]
name = "hw_01"
version = "0.1.0"
authors = ["Perestoronin Pavel <pavel.perestoronin@qoollo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "^0"
log = "^0"
termion = "^1"
rand = "^0"
